### ISSUE TITLE
You need to make a new workflow to get the latest version from the repository.

### ISSUE THREAD

**Issue by gabriel-aplok** [bedrock-dot-dev/packs#2]
You need to make a new workflow to get the latest version from the [repository](https://github.com/Mojang/bedrock-samples/releases).

mojang has changed the way packs are downloaded, ie **aka.ms** will be redirected to the [github repository](https://github.com/Mojang/bedrock-samples/releases), causing **bedrock.dev** to no longer download packs.

please do something 😩

**Comment by GTB3NW** [comment]
@destruc7i0n

**Comment by destruc7i0n** [comment]
I updated the messages on https://bedrock.dev/packs to point to the Official Mojang/bedrock-samples repo. This repo will no longer be updated
